name: Android CI

on:
  push:
    branches: [ "Amethyst-Stable" ]
  pull_request:
    branches: [ "Amethyst-Stable" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Build
        run: ./gradlew assembleDebug
